//    Copyright (C) 2012 Dirk Vanden Boer <dirk.vdb@gmail.com>
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#pragma once

#include <sstream>
#include <string>
#include <vector>

namespace upnp
{
namespace test
{
namespace testxmls
{

static const std::string gatewayRootDesc =
"<?xml version=\"1.0\"?>"
"<root xmlns=\"urn:schemas-upnp-org:device-1-0\">"
"    <specVersion>"
"        <major>1</major>"
"        <minor>0</minor>"
"    </specVersion>"
"    <device>"
"        <deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType>"
"        <friendlyName>Compal Broadband Networks, Inc CH6643</friendlyName>"
"        <manufacturer>Compal Broadband Networks, Inc</manufacturer>"
"        <manufacturerURL>http://www.icbn.com.tw</manufacturerURL>"
"        <modelDescription> CH6643</modelDescription>"
"        <modelName> CH6643</modelName>"
"        <modelNumber>CH6643</modelNumber>"
"        <modelURL>http://www.icbn.com.tw</modelURL>"
"        <serialNumber>601581307023619400000660</serialNumber>"
"        <UDN>uuid:A37351C5-8521-4c24-A43E-5C353B9982A9</UDN>"
"        <serviceList>"
"            <service>"
"                <serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType>"
"                <serviceId>urn:upnp-org:serviceId:Layer3Forwarding1</serviceId>"
"                <controlURL>/ctl/L3F</controlURL>"
"                <eventSubURL>/evt/L3F</eventSubURL>"
"                <SCPDURL>/L3F.xml</SCPDURL>"
"            </service>"
"        </serviceList>"
"    </device>"
"</root>";

static const std::string mediaServerRootDesc =
"<?xml version=\"1.0\" encoding=\"UTF-8\" ?>"
"<root xmlns=\"urn:schemas-upnp-org:device-1-0\">"
"   <specVersion>"
"       <major>1</major>"
"       <minor>0</minor>"
"   </specVersion>"
"   <device>"
"       <dlna:X_DLNADOC xmlns:dlna=\"urn:schemas-dlna-org:device-1-0\">DMS-1.50</dlna:X_DLNADOC>"
"       <dlna:X_DLNADOC xmlns:dlna=\"urn:schemas-dlna-org:device-1-0\">M-DMS-1.50</dlna:X_DLNADOC>"
"       <pv:extension xmlns:pv=\"http://www.pv.com/pvns/\"></pv:extension><pv:platformID xmlns:pv=\"http://www.pv.com/pvns/\">Linux 3.4.6; armv5tel</pv:platformID><deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>"
"       <UDN>uuid:55076f6e-6b79-1d65-a4eb-00089be34071</UDN>"
"       <friendlyName>NAS</friendlyName>"
"       <manufacturer>PacketVideo</manufacturer>"
"       <manufacturerURL>http://www.pv.com</manufacturerURL>"
"       <modelName>TwonkyServer</modelName>"
"       <modelURL>http://www.twonky.com</modelURL>"
"       <modelDescription>TwonkyServer (Linux, T2)</modelDescription>"
"       <modelNumber>8.2</modelNumber>"
"       <serialNumber>8.2</serialNumber>"
"       <UPC></UPC>"
"       <presentationURL>http://192.168.1.13:9000/</presentationURL>"
"       <iconList>"
"           <icon>"
"               <mimetype>image/jpeg</mimetype>"
"               <height>48</height>"
"               <width>48</width>"
"               <depth>24</depth>"
"               <url>/images/twonkyicon-48x48.jpg</url>"
"           </icon>"
"           <icon>"
"               <mimetype>image/jpeg</mimetype>"
"               <height>120</height>"
"               <width>120</width>"
"               <depth>24</depth>"
"               <url>/images/twonkyicon-120x120.jpg</url>"
"           </icon>"
"           <icon>"
"               <mimetype>image/png</mimetype>"
"               <height>48</height>"
"               <width>48</width>"
"               <depth>24</depth>"
"               <url>/images/twonkyicon-48x48.png</url>"
"           </icon>"
"           <icon>"
"               <mimetype>image/png</mimetype>"
"               <height>120</height>"
"               <width>120</width>"
"               <depth>24</depth>"
"               <url>/images/twonkyicon-120x120.png</url>"
"           </icon>"
"       </iconList>"
"       <serviceList>"
"           <service>"
"               <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>"
"               <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>"
"               <SCPDURL>/dev0/srv0.xml</SCPDURL>"
"               <eventSubURL>/dev0/srv0/event</eventSubURL>"
"               <controlURL>/dev0/srv0/control</controlURL>"
"           </service>"
"           <service>"
"               <serviceType>urn:schemas-upnp-org:service:ContentDirectory:1</serviceType>"
"               <serviceId>urn:upnp-org:serviceId:ContentDirectory</serviceId>"
"               <SCPDURL>/dev0/srv1.xml</SCPDURL>"
"               <eventSubURL>/dev0/srv1/event</eventSubURL>"
"               <controlURL>/dev0/srv1/control</controlURL>"
"           </service>"
"           <service>"
"               <serviceType>urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1</serviceType>"
"               <serviceId>urn:microsoft.com:serviceId:X_MS_MediaReceiverRegistrar</serviceId>"
"               <SCPDURL>/dev0/srv2.xml</SCPDURL>"
"               <eventSubURL>/dev0/srv2/event</eventSubURL>"
"               <controlURL>/dev0/srv2/control</controlURL>"
"           </service>"
"       </serviceList>"
"   </device>"
"</root>";

static std::string simpleServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd"
"  xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"   <specVersion>"
"       <major>1</major>"
"       <minor>0</minor>"
"   </specVersion>"
"   <actionList>"
"       <action>"
"           <name>Action1</name>"
"           <argumentList>"
"               <argument>"
"                   <name>Var</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>Variable1</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>Action2</name>"
"           <argumentList>"
"               <argument>"
"                   <name>Var</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>Variable1</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"   </actionList>"
"   <serviceStateTable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>Variable1</name>"
"           <dataType>ui4</dataType>"
"       </stateVariable>"
"   </serviceStateTable>"
"</scpd>";


static std::string renderingServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd"
"  xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"   <specVersion>"
"       <major>1</major>"
"       <minor>0</minor>"
"   </specVersion>"
"   <actionList>"
"       <action>"
"           <name>ListPresets</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentPresetNameList</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>PresetNameList</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>SelectPreset</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>PresetName</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_PresetName</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>GetMute</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Channel</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentMute</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>Mute</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>SetMute</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Channel</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>DesiredMute</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>Mute</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>GetVolume</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Channel</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentVolume</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>Volume</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>SetVolume</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Channel</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>DesiredVolume</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>Volume</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"   </actionList>"
"   <serviceStateTable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>PresetNameList</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"yes\">"
"           <name>LastChange</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>Mute</name>"
"           <dataType>boolean</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>Volume</name>"
"           <dataType>ui2</dataType>"
"           <allowedValueRange>"
"               <minimum>10</minimum>"
"               <maximum>110</maximum>"
"               <step>1</step>"
"           </allowedValueRange>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>A_ARG_TYPE_Channel</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>Master</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>A_ARG_TYPE_InstanceID</name>"
"           <dataType>ui4</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>A_ARG_TYPE_PresetName</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>FactoryDefaults</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"   </serviceStateTable>"
"</scpd>";

static std::string avtransportServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd"
"  xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"   <specVersion>"
"       <major>1</major>"
"       <minor>0</minor>"
"   </specVersion>"
"   <actionList>"
"       <action>"
"           <name>SetAVTransportURI</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentURI</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>AVTransportURI</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentURIMetaData</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>GetMediaInfo</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>NrTracks</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>NumberOfTracks</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>MediaDuration</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>CurrentMediaDuration</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentURI</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>AVTransportURI</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentURIMetaData</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>NextURI</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>NextAVTransportURI</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>NextURIMetaData</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>NextAVTransportURIMetaData</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>PlayMedium</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>PlaybackStorageMedium</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>RecordMedium</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>RecordStorageMedium</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>WriteStatus</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>RecordMediumWriteStatus</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>GetTransportInfo</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentTransportState</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>TransportState</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentTransportStatus</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>TransportStatus</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>CurrentSpeed</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>TransportPlaySpeed</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>GetPositionInfo</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Track</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>CurrentTrack</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>TrackDuration</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>CurrentTrackDuration</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>TrackMetaData</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>CurrentTrackMetaData</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>TrackURI</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>CurrentTrackURI</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>RelTime</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>RelativeTimePosition</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>AbsTime</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>AbsoluteTimePosition</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>RelCount</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>RelativeCounterPosition</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>AbsCount</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>AbsoluteCounterPosition</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>GetDeviceCapabilities</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>PlayMedia</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>PossiblePlaybackStorageMedia</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>RecMedia</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>PossibleRecordStorageMedia</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>RecQualityModes</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>PossibleRecordQualityModes</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>GetTransportSettings</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>PlayMode</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>CurrentPlayMode</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>RecQualityMode</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>CurrentRecordQualityMode</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>Stop</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>Play</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Speed</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>TransportPlaySpeed</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>Pause</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>Seek</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Unit</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_SeekMode</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Target</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_SeekTarget</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>Next</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>Previous</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>SetPlayMode</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>NewPlayMode</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>CurrentPlayMode</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"       <action>"
"           <name>GetCurrentTransportActions</name>"
"           <argumentList>"
"               <argument>"
"                   <name>InstanceID</name>"
"                   <direction>in</direction>"
"                   <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"               </argument>"
"               <argument>"
"                   <name>Actions</name>"
"                   <direction>out</direction>"
"                   <relatedStateVariable>CurrentTransportActions</relatedStateVariable>"
"               </argument>"
"           </argumentList>"
"       </action>"
"   </actionList>"
"   <serviceStateTable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>TransportState</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>STOPPED</allowedValue>"
"               <allowedValue>PLAYING</allowedValue>"
"               <allowedValue>PAUSED_PLAYBACK</allowedValue>"
"               <allowedValue>TRANSITIONING</allowedValue>"
"               <allowedValue>NO_MEDIA_PRESENT</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>TransportStatus</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>OK</allowedValue>"
"               <allowedValue>ERROR_OCCURRED</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>PlaybackStorageMedium</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>NETWORK</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>RecordStorageMedium</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>NOT_IMPLEMENTED</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>PossiblePlaybackStorageMedia</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>PossibleRecordStorageMedia</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>CurrentPlayMode</name>"
"           <dataType>string</dataType>"
"           <defaultValue>NORMAL</defaultValue>"
"           <allowedValueList>"
"               <allowedValue>NORMAL</allowedValue>"
"               <allowedValue>SHUFFLE</allowedValue>"
"               <allowedValue>REPEAT_ONE</allowedValue>"
"               <allowedValue>REPEAT_ALL</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>TransportPlaySpeed</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>1</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>RecordMediumWriteStatus</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>NOT_IMPLEMENTED</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>CurrentRecordQualityMode</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>NOT_IMPLEMENTED</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>PossibleRecordQualityModes</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>NumberOfTracks</name>"
"           <dataType>ui4</dataType>"
"           <allowedValueRange>"
"               <minimum>0</minimum>"
"               <maximum>1</maximum>"
"           </allowedValueRange>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>CurrentTrack</name>"
"           <dataType>ui4</dataType>"
"           <allowedValueRange>"
"               <minimum>0</minimum>"
"               <maximum>1</maximum>"
"               <step>1</step>"
"           </allowedValueRange>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>CurrentTrackDuration</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>CurrentMediaDuration</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>CurrentTrackMetaData</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>CurrentTrackURI</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>AVTransportURI</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>AVTransportURIMetaData</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>NextAVTransportURI</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>NextAVTransportURIMetaData</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>RelativeTimePosition</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>AbsoluteTimePosition</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>RelativeCounterPosition</name>"
"           <dataType>i4</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>AbsoluteCounterPosition</name>"
"           <dataType>i4</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>CurrentTransportActions</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"yes\">"
"           <name>LastChange</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>A_ARG_TYPE_SeekMode</name>"
"           <dataType>string</dataType>"
"           <allowedValueList>"
"               <allowedValue>TRACK_NR</allowedValue>"
"           </allowedValueList>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>A_ARG_TYPE_SeekTarget</name>"
"           <dataType>string</dataType>"
"       </stateVariable>"
"       <stateVariable sendEvents=\"no\">"
"           <name>A_ARG_TYPE_InstanceID</name>"
"           <dataType>ui4</dataType>"
"       </stateVariable>"
"   </serviceStateTable>"
"</scpd>";

static const std::string contentDirectoryServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"    <specVersion>"
"        <major>1</major>"
"        <minor>0</minor>"
"    </specVersion>"
"    <actionList>"
"        <action>"
"            <name>GetSearchCapabilities</name>"
"            <argumentList>"
"                <argument>"
"                    <name>SearchCaps</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>SearchCapabilities</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>GetSortCapabilities</name>"
"            <argumentList>"
"                <argument>"
"                    <name>SortCaps</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>SortCapabilities</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>GetSystemUpdateID</name>"
"            <argumentList>"
"                <argument>"
"                    <name>Id</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>SystemUpdateID</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>Browse</name>"
"            <argumentList>"
"                <argument>"
"                    <name>ObjectID</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>BrowseFlag</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_BrowseFlag</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Filter</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Filter</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>StartingIndex</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Index</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>RequestedCount</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>SortCriteria</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_SortCriteria</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Result</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>NumberReturned</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>TotalMatches</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>UpdateID</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_UpdateID</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>Search</name>"
"            <argumentList>"
"                <argument>"
"                    <name>ContainerID</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>SearchCriteria</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_SearchCriteria</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Filter</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Filter</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>StartingIndex</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Index</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>RequestedCount</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>SortCriteria</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_SortCriteria</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Result</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>NumberReturned</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>TotalMatches</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>UpdateID</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_UpdateID</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"    </actionList>"
"    <serviceStateTable>"
"        <stateVariable sendEvents=\"yes\">"
"            <name>TransferIDs</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_ObjectID</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Result</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_SearchCriteria</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_BrowseFlag</name>"
"            <dataType>string</dataType>"
"            <allowedValueList>"
"                <allowedValue>BrowseMetadata</allowedValue>"
"                <allowedValue>BrowseDirectChildren</allowedValue>"
"            </allowedValueList>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Filter</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_SortCriteria</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Index</name>"
"            <dataType>ui4</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Count</name>"
"            <dataType>ui4</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_UpdateID</name>"
"            <dataType>ui4</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>SearchCapabilities</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>SortCapabilities</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"yes\">"
"            <name>SystemUpdateID</name>"
"            <dataType>ui4</dataType>"
"        </stateVariable>"
"    </serviceStateTable>"
"</scpd>";

static const std::string connectionManagerServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd"
"  xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"    <specVersion>"
"        <major>1</major>"
"        <minor>0</minor>"
"    </specVersion>"
"    <actionList>"
"        <action>"
"            <name>GetProtocolInfo</name>"
"            <argumentList>"
"                <argument>"
"                    <name>Source</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>SourceProtocolInfo</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Sink</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>SinkProtocolInfo</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>GetCurrentConnectionIDs</name>"
"            <argumentList>"
"                <argument>"
"                    <name>ConnectionIDs</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>CurrentConnectionIDs</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>GetCurrentConnectionInfo</name>"
"            <argumentList>"
"                <argument>"
"                    <name>ConnectionID</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ConnectionID</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>RcsID</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_RcsID</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>AVTransportID</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_AVTransportID</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>ProtocolInfo</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ProtocolInfo</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>PeerConnectionManager</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ConnectionManager</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>PeerConnectionID</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ConnectionID</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Direction</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Direction</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Status</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ConnectionStatus</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"    </actionList>"
"    <serviceStateTable>"
"        <stateVariable sendEvents=\"yes\">"
"            <name>SourceProtocolInfo</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"yes\">"
"            <name>SinkProtocolInfo</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"yes\">"
"            <name>CurrentConnectionIDs</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_ConnectionStatus</name>"
"            <dataType>string</dataType>"
"            <allowedValueList>"
"                <allowedValue>OK</allowedValue>"
"                <allowedValue>ContentFormatMismatch</allowedValue>"
"                <allowedValue>InsufficientBandwidth</allowedValue>"
"                <allowedValue>UnreliableChannel</allowedValue>"
"                <allowedValue>Unknown</allowedValue>"
"            </allowedValueList>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_ConnectionManager</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Direction</name>"
"            <dataType>string</dataType>"
"            <allowedValueList>"
"                <allowedValue>Input</allowedValue>"
"                <allowedValue>Output</allowedValue>"
"            </allowedValueList>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_ProtocolInfo</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_ConnectionID</name>"
"            <dataType>i4</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_AVTransportID</name>"
"            <dataType>i4</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_RcsID</name>"
"            <dataType>i4</dataType>"
"        </stateVariable>"
"    </serviceStateTable>"
"</scpd>";

static const std::string browseRequest =
"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">"
"<s:Body><u:Browse xmlns:u=\"urn:schemas-upnp-org:service:ContentDirectory:1\">"
"<BrowseFlag>BrowseDirectChildren</BrowseFlag>"
"<Filter>*</Filter>"
"<ObjectID>0$1$12$38502</ObjectID>"
"<RequestedCount>32</RequestedCount>"
"<SortCriteria></SortCriteria>"
"<StartingIndex>0</StartingIndex>"
"</u:Browse>"
"</s:Body>"
"</s:Envelope>";

static const std::string browseResponseItems =
"<u:BrowseResponse xmlns:u=\"urn:schemas-upnp-org:service:ContentDirectory:1\">"
"    <Result>&lt;DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:dlna=\"urn:schemas-dlna-org:metadata-1-0/\" xmlns:arib=\"urn:schemas-arib-or-jp:elements-1-0/\" xmlns:dtcp=\"urn:schemas-dtcp-com:metadata-1-0/\" xmlns:pv=\"http://www.pv.com/pvns/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"&gt;"
"&lt;item id=&quot;0$1$12$38502R2290700&quot; refID=&quot;0$1$8I2290700&quot; parentID=&quot;0$1$12$38502&quot; restricted=&quot;1&quot;&gt;&lt;dc:title&gt;Momove&lt;/dc:title&gt;&lt;dc:date&gt;2002-01-01&lt;/dc:date&gt;&lt;upnp:genre&gt;Club&lt;/upnp:genre&gt;&lt;upnp:album&gt;A Hundred Days Off&lt;/upnp:album&gt;&lt;upnp:originalTrackNumber&gt;1&lt;/upnp:originalTrackNumber&gt;&lt;dc:creator&gt;Underworld&lt;/dc:creator&gt;&lt;upnp:albumArtURI dlna:profileID=\"JPEG_TN\" &gt;http://192.168.1.13:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/A/O0$1$8I2290700.jpg?scale=org&lt;/upnp:albumArtURI&gt;&lt;upnp:artist&gt;Underworld&lt;/upnp:artist&gt;&lt;upnp:albumArtist&gt;Underworld&lt;/upnp:albumArtist&gt;&lt;pv:playcount&gt;1&lt;/pv:playcount&gt;&lt;pv:modificationTime&gt;1133382780&lt;/pv:modificationTime&gt;&lt;pv:addedTime&gt;1438685937&lt;/pv:addedTime&gt;&lt;pv:lastPlayedTime&gt;2015-12-31T22:54:22&lt;/pv:lastPlayedTime&gt;&lt;pv:numberOfThisDisc&gt;1&lt;/pv:numberOfThisDisc&gt;&lt;pv:extension&gt;mp3&lt;/pv:extension&gt;&lt;pv:bookmark&gt;uuid:55076f6e-6b79-1d65-a4eb-00089be34071,-L3NoYXJlL011bHRpbWVkaWEvbXVzaWMvVW5kZXJ3b3JsZCAtIEEgSHVuZHJlZCBEYXlzIE9mZiAoMjAwMikvMDEgLSBVbmRlcndvcmxkIC0gTW9tb3ZlLm1wMw==&lt;/pv:bookmark&gt;&lt;res duration=\"0:06:54\" size=\"10053760\" bitrate=\"24000\" protocolInfo=\"http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=11;DLNA.ORG_FLAGS=01700000000000000000000000000000\" pv:timeseekinfo=\"http://192.168.1.13:9000/disk/O0$1$12$38502R2290700.seek\" &gt;http://192.168.1.13:9000/disk/DLNA-PNMP3-OP11-FLAGS01700000/O0$1$8I2290700.mp3&lt;/res&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;/item&gt;"
"&lt;item id=&quot;0$1$12$38502R2291724&quot; refID=&quot;0$1$8I2291724&quot; parentID=&quot;0$1$12$38502&quot; restricted=&quot;0&quot;&gt;&lt;dc:title&gt;Two Months Off&lt;/dc:title&gt;&lt;dc:date&gt;2002-01-01&lt;/dc:date&gt;&lt;upnp:genre&gt;Club&lt;/upnp:genre&gt;&lt;upnp:album&gt;A Hundred Days Off&lt;/upnp:album&gt;&lt;upnp:originalTrackNumber&gt;2&lt;/upnp:originalTrackNumber&gt;&lt;dc:creator&gt;Underworld&lt;/dc:creator&gt;&lt;upnp:albumArtURI dlna:profileID=\"JPEG_TN\" &gt;http://192.168.1.13:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/A/O0$1$8I2291724.jpg?scale=org&lt;/upnp:albumArtURI&gt;&lt;upnp:artist&gt;Underworld&lt;/upnp:artist&gt;&lt;upnp:albumArtist&gt;Underworld&lt;/upnp:albumArtist&gt;&lt;pv:modificationTime&gt;1133382778&lt;/pv:modificationTime&gt;&lt;pv:addedTime&gt;1438685937&lt;/pv:addedTime&gt;&lt;pv:numberOfThisDisc&gt;1&lt;/pv:numberOfThisDisc&gt;&lt;pv:extension&gt;mp3&lt;/pv:extension&gt;&lt;pv:bookmark&gt;uuid:55076f6e-6b79-1d65-a4eb-00089be34071,-L3NoYXJlL011bHRpbWVkaWEvbXVzaWMvVW5kZXJ3b3JsZCAtIEEgSHVuZHJlZCBEYXlzIE9mZiAoMjAwMikvMDIgLSBVbmRlcndvcmxkIC0gVHdvIE1vbnRocyBPZmYubXAz&lt;/pv:bookmark&gt;&lt;res duration=\"0:09:09\" size=\"13275264\" bitrate=\"24000\" protocolInfo=\"http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=11;DLNA.ORG_FLAGS=01700000000000000000000000000000\" pv:timeseekinfo=\"http://192.168.1.13:9000/disk/O0$1$12$38502R2291724.seek\" &gt;http://192.168.1.13:9000/disk/DLNA-PNMP3-OP11-FLAGS01700000/O0$1$8I2291724.mp3&lt;/res&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;/item&gt;"
"&lt;/DIDL-Lite&gt;</Result>"
"    <NumberReturned>2</NumberReturned>"
"    <TotalMatches>12</TotalMatches>"
"    <UpdateID>2</UpdateID>"
"</u:BrowseResponse>";

static const std::string browseResponseContainers =
"<u:BrowseResponse xmlns:u=\"urn:schemas-upnp-org:service:ContentDirectory:1\">"
"    <Result>&lt;DIDL-Lite xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:upnp=\"urn:schemas-upnp-org:metadata-1-0/upnp/\" xmlns:dlna=\"urn:schemas-dlna-org:metadata-1-0/\" xmlns:arib=\"urn:schemas-arib-or-jp:elements-1-0/\" xmlns:dtcp=\"urn:schemas-dtcp-com:metadata-1-0/\" xmlns:pv=\"http://www.pv.com/pvns/\" xmlns=\"urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/\"&gt;"
"&lt;container id=\"0$1$17$994$23308\" parentID=\"0$1$17$994\" restricted=\"1\" childCount=\"12\" searchable=\"1\"&gt;&lt;dc:title&gt;+DOME&lt;/dc:title&gt;&lt;upnp:genre&gt;Dubstep, Indie, Experimental, Ambient&lt;/upnp:genre&gt;&lt;upnp:album&gt;+DOME&lt;/upnp:album&gt;&lt;dc:creator&gt;Seekae&lt;/dc:creator&gt;&lt;upnp:albumArtURI dlna:profileID=\"JPEG_TN\" &gt;http://192.168.1.13:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/C/O0$1$17$994$23308.jpg?scale=org&lt;/upnp:albumArtURI&gt;&lt;pv:childCountContainer&gt;0&lt;/pv:childCountContainer&gt;&lt;upnp:artist&gt;Seekae&lt;/upnp:artist&gt;&lt;pv:modificationTime&gt;59813&lt;/pv:modificationTime&gt;&lt;pv:containerContent&gt;object.item.audioItem.musicTrack&lt;/pv:containerContent&gt;&lt;upnp:class&gt;object.container.album.musicAlbum&lt;/upnp:class&gt;&lt;/container&gt;"
"&lt;container id=\"0$1$17$994$20156\" parentID=\"0$1$17$994\" restricted=\"0\" childCount=\"11\" searchable=\"1\"&gt;&lt;dc:title&gt;My Favorite Things&lt;/dc:title&gt;&lt;upnp:genre&gt;Broken Beat, Deep House, Experimental, Ambient&lt;/upnp:genre&gt;&lt;upnp:album&gt;My Favorite Things&lt;/upnp:album&gt;&lt;dc:creator&gt;Toshiya Kawasaki&lt;/dc:creator&gt;&lt;upnp:albumArtURI dlna:profileID=\"JPEG_TN\" &gt;http://192.168.1.13:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/C/O0$1$17$994$20156.jpg?scale=org&lt;/upnp:albumArtURI&gt;&lt;pv:childCountContainer&gt;0&lt;/pv:childCountContainer&gt;&lt;upnp:artist&gt;Toshiya Kawasaki&lt;/upnp:artist&gt;&lt;pv:modificationTime&gt;51920&lt;/pv:modificationTime&gt;&lt;pv:containerContent&gt;object.item.audioItem.musicTrack&lt;/pv:containerContent&gt;&lt;upnp:class&gt;object.container.album.musicAlbum&lt;/upnp:class&gt;&lt;/container&gt;"
"&lt;/DIDL-Lite&gt;</Result>"
"    <NumberReturned>2</NumberReturned>"
"    <TotalMatches>3</TotalMatches>"
"    <UpdateID>4</UpdateID>"
"</u:BrowseResponse>";

struct EventValue
{
    EventValue(const std::string& eventName, const std::string& eventValue)
    : name(eventName)
    , value(eventValue)
    {}

    EventValue(const std::string& eventName, const std::string& eventValue, const std::map<std::string, std::string>& attrs)
    : name(eventName)
    , value(eventValue)
    , attributes(attrs)
    {}

    std::string name;
    std::string value;
    std::map<std::string, std::string> attributes;
};

namespace
{

void addAttribute(std::stringstream& ss, const std::string& name, const std::string& value)
{
    ss << " " << name << "=&quot;" << value << "&quot;";
}

void addValue(std::stringstream& ss, const EventValue& event)
{
    ss << "            &lt;" << event.name;
    for (auto& attr : event.attributes)
    {
        addAttribute(ss, attr.first, attr.second);
    }

    addAttribute(ss, "val", event.value);

    ss << "/&gt;" << std::endl;
}

}

inline std::string generateStateVariableChangeEvent(const std::string& changedVar, const std::string& namespaceId, const std::vector<EventValue>& values)
{
    std::stringstream ss;
    ss << "<e:propertyset xmlns:e=\"urn:schemas-upnp-org:event-1-0\">" << std::endl
       << "<e:property>" << std::endl
       << "    <" << changedVar << ">&lt;Event xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/" << namespaceId << "/&quot;&gt;" << std::endl
       << "        &lt;InstanceID val=&quot;0&quot;&gt;" << std::endl;

    for (auto& value : values)
    {
        addValue(ss, value);
    }

    ss << "        &lt;/InstanceID&gt;" << std::endl;
    ss << "    &lt;/Event&gt;</" << changedVar << ">" << std::endl;
    ss << "</e:property>" << std::endl;
    ss << "</e:propertyset>" << std::endl;

    return ss.str();
}

}
}
}
