//    Copyright (C) 2012 Dirk Vanden Boer <dirk.vdb@gmail.com>
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#ifndef TEST_XMLS_H
#define TEST_XMLS_H

namespace upnp
{
namespace test
{
namespace testxmls
{

static std::string simpleServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd"
"  xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"	<specVersion>"
"		<major>1</major>"
"		<minor>0</minor>"
"	</specVersion>"
"	<actionList>"
"		<action>"
"			<name>Action1</name>"
"			<argumentList>"
"				<argument>"
"					<name>Var</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>Variable1</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>Action2</name>"
"			<argumentList>"
"				<argument>"
"					<name>Var</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>Variable1</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"	</actionList>"
"	<serviceStateTable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>Variable1</name>"
"			<dataType>ui4</dataType>"
"		</stateVariable>"
"	</serviceStateTable>"
"</scpd>";

    
static std::string renderingServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd"
"  xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"	<specVersion>"
"		<major>1</major>"
"		<minor>0</minor>"
"	</specVersion>"
"	<actionList>"
"		<action>"
"			<name>ListPresets</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentPresetNameList</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>PresetNameList</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>SelectPreset</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>PresetName</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_PresetName</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>GetMute</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Channel</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentMute</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>Mute</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>SetMute</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Channel</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>DesiredMute</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>Mute</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>GetVolume</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Channel</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentVolume</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>Volume</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>SetVolume</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Channel</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>DesiredVolume</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>Volume</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"	</actionList>"
"	<serviceStateTable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>PresetNameList</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"yes\">"
"			<name>LastChange</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>Mute</name>"
"			<dataType>boolean</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>Volume</name>"
"			<dataType>ui2</dataType>"
"			<allowedValueRange>"
"				<minimum>10</minimum>"
"				<maximum>110</maximum>"
"				<step>1</step>"
"			</allowedValueRange>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>A_ARG_TYPE_Channel</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>Master</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>A_ARG_TYPE_InstanceID</name>"
"			<dataType>ui4</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>A_ARG_TYPE_PresetName</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>FactoryDefaults</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"	</serviceStateTable>"
"</scpd>";

static std::string avtransportServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd"
"  xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"	<specVersion>"
"		<major>1</major>"
"		<minor>0</minor>"
"	</specVersion>"
"	<actionList>"
"		<action>"
"			<name>SetAVTransportURI</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentURI</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>AVTransportURI</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentURIMetaData</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>GetMediaInfo</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>NrTracks</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>NumberOfTracks</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>MediaDuration</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>CurrentMediaDuration</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentURI</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>AVTransportURI</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentURIMetaData</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>NextURI</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>NextAVTransportURI</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>NextURIMetaData</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>NextAVTransportURIMetaData</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>PlayMedium</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>PlaybackStorageMedium</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>RecordMedium</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>RecordStorageMedium</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>WriteStatus</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>RecordMediumWriteStatus</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>GetTransportInfo</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentTransportState</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>TransportState</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentTransportStatus</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>TransportStatus</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>CurrentSpeed</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>TransportPlaySpeed</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>GetPositionInfo</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Track</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>CurrentTrack</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>TrackDuration</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>CurrentTrackDuration</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>TrackMetaData</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>CurrentTrackMetaData</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>TrackURI</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>CurrentTrackURI</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>RelTime</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>RelativeTimePosition</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>AbsTime</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>AbsoluteTimePosition</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>RelCount</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>RelativeCounterPosition</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>AbsCount</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>AbsoluteCounterPosition</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>GetDeviceCapabilities</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>PlayMedia</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>PossiblePlaybackStorageMedia</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>RecMedia</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>PossibleRecordStorageMedia</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>RecQualityModes</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>PossibleRecordQualityModes</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>GetTransportSettings</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>PlayMode</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>CurrentPlayMode</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>RecQualityMode</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>CurrentRecordQualityMode</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>Stop</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>Play</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Speed</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>TransportPlaySpeed</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>Pause</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>Seek</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Unit</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_SeekMode</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Target</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_SeekTarget</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>Next</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>Previous</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>SetPlayMode</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>NewPlayMode</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>CurrentPlayMode</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"		<action>"
"			<name>GetCurrentTransportActions</name>"
"			<argumentList>"
"				<argument>"
"					<name>InstanceID</name>"
"					<direction>in</direction>"
"					<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>"
"				</argument>"
"				<argument>"
"					<name>Actions</name>"
"					<direction>out</direction>"
"					<relatedStateVariable>CurrentTransportActions</relatedStateVariable>"
"				</argument>"
"			</argumentList>"
"		</action>"
"	</actionList>"
"	<serviceStateTable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>TransportState</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>STOPPED</allowedValue>"
"				<allowedValue>PLAYING</allowedValue>"
"				<allowedValue>PAUSED_PLAYBACK</allowedValue>"
"				<allowedValue>TRANSITIONING</allowedValue>"
"				<allowedValue>NO_MEDIA_PRESENT</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>TransportStatus</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>OK</allowedValue>"
"				<allowedValue>ERROR_OCCURRED</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>PlaybackStorageMedium</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>NETWORK</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>RecordStorageMedium</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>NOT_IMPLEMENTED</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>PossiblePlaybackStorageMedia</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>PossibleRecordStorageMedia</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>CurrentPlayMode</name>"
"			<dataType>string</dataType>"
"			<defaultValue>NORMAL</defaultValue>"
"			<allowedValueList>"
"				<allowedValue>NORMAL</allowedValue>"
"				<allowedValue>SHUFFLE</allowedValue>"
"				<allowedValue>REPEAT_ONE</allowedValue>"
"				<allowedValue>REPEAT_ALL</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>TransportPlaySpeed</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>1</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>RecordMediumWriteStatus</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>NOT_IMPLEMENTED</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>CurrentRecordQualityMode</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>NOT_IMPLEMENTED</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>PossibleRecordQualityModes</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>NumberOfTracks</name>"
"			<dataType>ui4</dataType>"
"			<allowedValueRange>"
"				<minimum>0</minimum>"
"				<maximum>1</maximum>"
"			</allowedValueRange>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>CurrentTrack</name>"
"			<dataType>ui4</dataType>"
"			<allowedValueRange>"
"				<minimum>0</minimum>"
"				<maximum>1</maximum>"
"				<step>1</step>"
"			</allowedValueRange>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>CurrentTrackDuration</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>CurrentMediaDuration</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>CurrentTrackMetaData</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>CurrentTrackURI</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>AVTransportURI</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>AVTransportURIMetaData</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>NextAVTransportURI</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>NextAVTransportURIMetaData</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>RelativeTimePosition</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>AbsoluteTimePosition</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>RelativeCounterPosition</name>"
"			<dataType>i4</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>AbsoluteCounterPosition</name>"
"			<dataType>i4</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>CurrentTransportActions</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"yes\">"
"			<name>LastChange</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>A_ARG_TYPE_SeekMode</name>"
"			<dataType>string</dataType>"
"			<allowedValueList>"
"				<allowedValue>TRACK_NR</allowedValue>"
"			</allowedValueList>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>A_ARG_TYPE_SeekTarget</name>"
"			<dataType>string</dataType>"
"		</stateVariable>"
"		<stateVariable sendEvents=\"no\">"
"			<name>A_ARG_TYPE_InstanceID</name>"
"			<dataType>ui4</dataType>"
"		</stateVariable>"
"	</serviceStateTable>"
"</scpd>";

static const std::string contentDirectoryServiceDescription =
"<?xml version=\"1.0\"?>"
"<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">"
"    <specVersion>"
"        <major>1</major>"
"        <minor>0</minor>"
"    </specVersion>"
"    <actionList>"
"        <action>"
"            <name>GetSearchCapabilities</name>"
"            <argumentList>"
"                <argument>"
"                    <name>SearchCaps</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>SearchCapabilities</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>GetSortCapabilities</name>"
"            <argumentList>"
"                <argument>"
"                    <name>SortCaps</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>SortCapabilities</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>GetSystemUpdateID</name>"
"            <argumentList>"
"                <argument>"
"                    <name>Id</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>SystemUpdateID</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>Browse</name>"
"            <argumentList>"
"                <argument>"
"                    <name>ObjectID</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>BrowseFlag</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_BrowseFlag</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Filter</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Filter</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>StartingIndex</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Index</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>RequestedCount</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>SortCriteria</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_SortCriteria</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Result</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>NumberReturned</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>TotalMatches</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>UpdateID</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_UpdateID</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"        <action>"
"            <name>Search</name>"
"            <argumentList>"
"                <argument>"
"                    <name>ContainerID</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_ObjectID</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>SearchCriteria</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_SearchCriteria</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Filter</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Filter</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>StartingIndex</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Index</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>RequestedCount</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>SortCriteria</name>"
"                    <direction>in</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_SortCriteria</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>Result</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Result</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>NumberReturned</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>TotalMatches</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_Count</relatedStateVariable>"
"                </argument>"
"                <argument>"
"                    <name>UpdateID</name>"
"                    <direction>out</direction>"
"                    <relatedStateVariable>A_ARG_TYPE_UpdateID</relatedStateVariable>"
"                </argument>"
"            </argumentList>"
"        </action>"
"    </actionList>"
"    <serviceStateTable>"
"        <stateVariable sendEvents=\"yes\">"
"            <name>TransferIDs</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_ObjectID</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Result</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_SearchCriteria</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_BrowseFlag</name>"
"            <dataType>string</dataType>"
"            <allowedValueList>"
"                <allowedValue>BrowseMetadata</allowedValue>"
"                <allowedValue>BrowseDirectChildren</allowedValue>"
"            </allowedValueList>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Filter</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_SortCriteria</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Index</name>"
"            <dataType>ui4</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_Count</name>"
"            <dataType>ui4</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>A_ARG_TYPE_UpdateID</name>"
"            <dataType>ui4</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>SearchCapabilities</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"no\">"
"            <name>SortCapabilities</name>"
"            <dataType>string</dataType>"
"        </stateVariable>"
"        <stateVariable sendEvents=\"yes\">"
"            <name>SystemUpdateID</name>"
"            <dataType>ui4</dataType>"
"        </stateVariable>"
"    </serviceStateTable>"
"</scpd>";


struct EventValue
{
    EventValue(const std::string& name, const std::string& value, const std::map<std::string, std::string>& attrs = {})
    : name(name)
    , value(value)
    , attributes(attrs)
    {}

    std::string name;
    std::string value;
    std::map<std::string, std::string> attributes;
};

namespace
{

void addAttribute(std::stringstream& ss, const std::string& name, const std::string& value)
{
    ss << " " << name << "=&quot;" << value << "&quot;";
}

void addValue(std::stringstream& ss, const EventValue& event)
{
    ss << "            &lt;" << event.name;
    for (auto& attr : event.attributes)
    {
        addAttribute(ss, attr.first, attr.second);
    }
    
    addAttribute(ss, "val", event.value);
    
    ss << "/&gt;" << std::endl;
}
    
}

inline std::string generateStateVariableChangeEvent(const std::string& changedVar, const std::string& namespaceId, const std::vector<EventValue>& values)
{
    std::stringstream ss;
    ss << "<e:propertyset xmlns:e=\"urn:schemas-upnp-org:event-1-0\">" << std::endl
       << "<e:property>" << std::endl
       << "    <" << changedVar << ">&lt;Event xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/" << namespaceId << "/&quot;&gt;" << std::endl
       << "        &lt;InstanceID val=&quot;0&quot;&gt;" << std::endl;

    for (auto& value : values)
    {
        addValue(ss, value);
    }
    
    ss << "        &lt;/InstanceID&gt;" << std::endl;
    ss << "    &lt;/Event&gt;</" << changedVar << ">" << std::endl;
    ss << "</e:property>" << std::endl;
    ss << "</e:propertyset>" << std::endl;
    
    return ss.str();
}

}
}
}

#endif
